### ISSUE TITLE
Error with http://eris.okfn.org/ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz

### ISSUE THREAD

**Issue by jtrillos** [maparent/virtuoso-python#15]
Hi, I was doing this installation but it generates an error. I think without this part I cannot do the test on RDFLib.
pip install http://eris.okfn.org/ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz

Collecting http://eris.okfn.org/ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9f438>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9f6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9f828>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9f9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9fb38>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz
Exception:
Traceback (most recent call last):
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
pip._vendor.requests.packages.urllib3.exceptions.NewConnectionError: <pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9fcf8>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='eris.okfn.org', port=80): Max retries exceeded with url: /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9fcf8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/jaimetrillos/Documents/BDO/virtuoso-python-master/pythonenv/lib/python3.5/site-packages/pip/_vendor/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
pip._vendor.requests.exceptions.ConnectionError: HTTPConnectionPool(host='eris.okfn.org', port=80): Max retries exceeded with url: /ww/2010/10/pyodbc-spasql/pyodbc-virtuoso-2.1.9-beta14.tar.gz (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7f3b63c9fcf8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by maparent** [comment]
It would depend on your ODBC connection string, your odbc.ini file, and your network configuration. 
I am not able to look at virtuoso issues for at least two weeks.
I am still hoping a maintainer will step up for this project.
